# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: generate_family_file.py 9179 2011-04-15 10:59:23Z xqt $
Configuration parameters:
  url = http://sfhomeless.wikia.com
  name = sfhomeless

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'sfhomeless'
        self.langs = {
            'en': u'sfhomeless.wikia.com',
        }

        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4]['en'] = [u'San Francisco Homeless Resource']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5]['en'] = [u'San Francisco Homeless Resource talk']
        self.namespaces[110] = self.namespaces.get(110, {})
        self.namespaces[110]['en'] = [u'Forum']
        self.namespaces[111] = self.namespaces.get(111, {})
        self.namespaces[111]['en'] = [u'Forum talk']
        self.namespaces[400] = self.namespaces.get(400, {})
        self.namespaces[400]['en'] = [u'Video']
        self.namespaces[401] = self.namespaces.get(401, {})
        self.namespaces[401]['en'] = [u'Video talk']
        self.namespaces[500] = self.namespaces.get(500, {})
        self.namespaces[500]['en'] = [u'User blog']
        self.namespaces[501] = self.namespaces.get(501, {})
        self.namespaces[501]['en'] = [u'User blog comment']
        self.namespaces[502] = self.namespaces.get(502, {})
        self.namespaces[502]['en'] = [u'Blog']
        self.namespaces[503] = self.namespaces.get(503, {})
        self.namespaces[503]['en'] = [u'Blog talk']


    def scriptpath(self, code):
        return {
            'en': u'',
        }[code]

    def version(self, code):
        return {
            'en': u'1.16.5',
        }[code]
